services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
    - 'POSTGRES_DB=mydatabase'
    - 'POSTGRES_PASSWORD=secret'
    - 'POSTGRES_USER=myuser'
    labels:
    - "org.springframework.boot.service-connection=postgres"
    ports:
    - '5432'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "16686:16686"
    - "4318:4318"
